version: "3.8"

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/symfony
    expose:
      - "9003"
    ports:
      - 8000:8000
    networks:
      - prueba

networks:
  prueba:
    driver: bridge
